### ISSUE TITLE
Relay from Telegram to Discord only

### ISSUE THREAD

**Issue by ph3l1x** [Suppen/TediCross#47]
Is it possible to only take messages from a specific person on telegram and broadcast it to the discord channel?

**Comment by trgwii** [comment]
I see an obvious solution here - Just set up the bot in a group on the Telegram side with the only members being the Telegram user and the bot. Would that solve your issue?

**Comment by molteber** [comment]
Can also just talk to the bot directly. But they will be able to relay messages back from discord too, so that's the problem here, if I understand the issue correct

**Comment by Jovaage** [comment]
These are all hacky solutions, which ofc would work.
I suggest we implement some broader settings to allow configuration like this.

**Comment by ph3l1x** [comment]
That would be nice. Thanks for the response guys.

**Comment by Suppen** [comment]
This is not a problem TediCross is trying to solve. TediCross is made to bridge a channel in Discord with one in Telegram so that it works like one big group chat. If it relays from only one person in a Telegram group, the Discord side will see just a fraction of an ongoing Telegram conversation. If you want to just join a Discord channel from Telegram, use a private chat with the bot.

As for bot permissions on the Discord side: The URL used to make the bot join the server has a number in it. The README of TediCross uses the number 248832. This number decides which permissions the bot gets. Use [this site](https://discordapi.com/permissions.html#248832) to get the number representing the permissions you want.

**Comment by Suppen** [comment]
The title problem is also fixable by manipulating the permissions of the Discord bot

**Comment by Suppen** [comment]
Actually, playing around with permissions a bit, I can't get it working. I would believe [1024](https://discordapi.com/permissions.html#1024) should make it Discord -> Telegram, and [247808](https://discordapi.com/permissions.html#247808) should make it Telegram -> Discord, but no matter what I try, it works both ways. Will do some more experimenting tomorrow

**Comment by mohsenkhanpour** [comment]
How is this issue going on? I would also like to be able to bridge only one way from a Telegram channel to discord server, because telegram channels are not discussion groups I would like to disable the relay to channel but still be able to relay to discord. Thanks for this awesome bot btw.

**Comment by Suppen** [comment]
Currently I'm just thinking about how to do it. It's a much requested feature, so it's probably the next big thing I do

**Comment by molteber** [comment]
Could be done the same way you relay joined messages, and for setup file the same way to.
```yml
bridges:
  - telegram:
      - relayMessages: false
```

**Comment by MakeMoneyOz** [comment]
Is there a way to only send from one Discord Chanel -> Telegram but not write the telegram messages back? 
so just a one way communications? I have two channels in Discord, one is a complete bridge, and once is just for announcements, so we obviously dont want to fill it will general chat from the other channel

**Comment by Suppen** [comment]
This has now (commit 1cc1cc4a02e1e6a9a74ea9c763235cec3edb2a60) been implemented

A new per-bridge-setting controls this: bridge.direction.
Setting it to "both" (default) makes the bridge work both ways.
Setting it to "d2t" makes it relay messages only from Discord to Telegram
Setting it to "t2d" makes it relay messages only from Telegram to Discord
